### ISSUE TITLE
irc moderation

### ISSUE THREAD

**Issue by dontlaugh** [saltstack/community#127]
Do you all intend to moderate Freenode IRC? Specifically #salt #salt-devel and #salt-offtopic

**Comment by sagetherage** [comment]
@waynew @garethgreenaway @Ch3LL are any of you in these channels? I will also check these channels on Freenode

**Comment by sagetherage** [comment]
We have let the community moderate on IRC and have several Core Team members in channels, is there a need for more moderation? @dontlaugh?

**Comment by waynew** [comment]
Freenode moderation is no longer possible, due to the decision of network operators to obliterate existing ops for channels mentioning Libera in their channel topic.

I don't know if anything has changed since then, but the last I knew, all of the channels are now the "off-topic" ##salt ##salt-devel, and ##salt-offtopic.
