### ISSUE TITLE
Verify default config options in Windows

### ISSUE THREAD

**Issue by twangboy** [saltstack/community#32]
Verify that removing the uncommented portions of the config file on Windows has no effect and that the values set in the config are actually the default values.

**Comment by markuskramerIgitt** [comment]
##  ipc_mode 
File C:\salt\conf\minion maybe formerly contained setting
    ipc_mode: tcp

It is now correctly set via variable `_DFLT_IPC_MODE` in [salt/config](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py)

File C:\salt\conf\minion contains the comment
    # Windows platforms lack posix IPC and must rely on slower TCP based inter-
    # process communications. Set ipc_mode to 'tcp' on such systems

The second sentence is misleading and should be changed.

File [SaltEvent](https://github.com/saltstack/salt/blob/2aa183284b9e85011706474c9cd65cf6d2125e13/salt/utils/event.py#L278) contains this check:

        if salt.utils.platform.is_windows() and 'ipc_mode' not in opts:
            self.opts['ipc_mode'] = 'tcp'

Could opts['ipc_mode'] disappear between two SaltEvents?
If this is meant as a self-test, why not only in salt/utils/verify.py?



## pki_dir
File C:\salt\conf\minion formerly contained
    pki_dir: /conf/pki/minion

This is not necessary because [salt/config]( https://github.com/saltstack/salt/blob/e18acb3c9f38c267a9b3dc7941b05b5821e2aa5d/salt/config/__init__.py#L1243) sets
    DEFAULT_MINION_OPTS = immutabletypes.freeze({
        'pki_dir': os.path.join(salt.syspaths.CONFIG_DIR, 'pki', 'minion'),
Regardless of the operating system.
This is OK for Windows

File C:\salt\conf\minion contains the comment
    # The directory to store the pki information in
    #pki_dir: /etc/salt/pki/minion

The default path for Windows is missing, this could be misleading.


## root_dir
To be discussed
